/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IDiamondCut {
  export type FacetCutStruct = {
    facetAddress: PromiseOrValue<string>;
    action: PromiseOrValue<BigNumberish>;
    functionSelectors: PromiseOrValue<BytesLike>[];
  };

  export type FacetCutStructOutput = [string, number, string[]] & {
    facetAddress: string;
    action: number;
    functionSelectors: string[];
  };
}

export interface DiamondCutFacetInterface extends utils.Interface {
  functions: {
    "diamondCut((address,uint8,bytes4[])[],address,bytes)": FunctionFragment;
    "updateSupportedInterfaces(bytes4[],bool[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "diamondCut" | "updateSupportedInterfaces"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "diamondCut",
    values: [
      IDiamondCut.FacetCutStruct[],
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSupportedInterfaces",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<boolean>[]]
  ): string;

  decodeFunctionResult(functionFragment: "diamondCut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateSupportedInterfaces",
    data: BytesLike
  ): Result;

  events: {
    "DiamondCut(tuple[],address,bytes)": EventFragment;
    "DiamondCut(tuple[],address,bytes)": EventFragment;
    "InterfaceSupportUpdated(bytes4,bool)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "DiamondCut(tuple[],address,bytes)"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DiamondCut(tuple[],address,bytes)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InterfaceSupportUpdated"): EventFragment;
}

export interface DiamondCut_tuple_array_address_bytes_EventObject {
  _diamondCut: IDiamondCut.FacetCutStructOutput[];
  _init: string;
  _calldata: string;
}
export type DiamondCut_tuple_array_address_bytes_Event = TypedEvent<
  [IDiamondCut.FacetCutStructOutput[], string, string],
  DiamondCut_tuple_array_address_bytes_EventObject
>;

export type DiamondCut_tuple_array_address_bytes_EventFilter =
  TypedEventFilter<DiamondCut_tuple_array_address_bytes_Event>;

export interface DiamondCut_tuple_array_address_bytes_EventObject {
  _diamondCut: IDiamondCut.FacetCutStructOutput[];
  _init: string;
  _calldata: string;
}
export type DiamondCut_tuple_array_address_bytes_Event = TypedEvent<
  [IDiamondCut.FacetCutStructOutput[], string, string],
  DiamondCut_tuple_array_address_bytes_EventObject
>;

export type DiamondCut_tuple_array_address_bytes_EventFilter =
  TypedEventFilter<DiamondCut_tuple_array_address_bytes_Event>;

export interface InterfaceSupportUpdatedEventObject {
  interfaceID: string;
  supported: boolean;
}
export type InterfaceSupportUpdatedEvent = TypedEvent<
  [string, boolean],
  InterfaceSupportUpdatedEventObject
>;

export type InterfaceSupportUpdatedEventFilter =
  TypedEventFilter<InterfaceSupportUpdatedEvent>;

export interface DiamondCutFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DiamondCutFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    diamondCut(
      _diamondCut: IDiamondCut.FacetCutStruct[],
      _init: PromiseOrValue<string>,
      _calldata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  diamondCut(
    _diamondCut: IDiamondCut.FacetCutStruct[],
    _init: PromiseOrValue<string>,
    _calldata: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateSupportedInterfaces(
    interfaceIDs: PromiseOrValue<BytesLike>[],
    support: PromiseOrValue<boolean>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    diamondCut(
      _diamondCut: IDiamondCut.FacetCutStruct[],
      _init: PromiseOrValue<string>,
      _calldata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DiamondCut(tuple[],address,bytes)"(
      _diamondCut?: null,
      _init?: null,
      _calldata?: null
    ): DiamondCut_tuple_array_address_bytes_EventFilter;
    "DiamondCut(tuple[],address,bytes)"(
      _diamondCut?: null,
      _init?: null,
      _calldata?: null
    ): DiamondCut_tuple_array_address_bytes_EventFilter;

    "InterfaceSupportUpdated(bytes4,bool)"(
      interfaceID?: PromiseOrValue<BytesLike> | null,
      supported?: null
    ): InterfaceSupportUpdatedEventFilter;
    InterfaceSupportUpdated(
      interfaceID?: PromiseOrValue<BytesLike> | null,
      supported?: null
    ): InterfaceSupportUpdatedEventFilter;
  };

  estimateGas: {
    diamondCut(
      _diamondCut: IDiamondCut.FacetCutStruct[],
      _init: PromiseOrValue<string>,
      _calldata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    diamondCut(
      _diamondCut: IDiamondCut.FacetCutStruct[],
      _init: PromiseOrValue<string>,
      _calldata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
