/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC165Updater,
  IERC165UpdaterInterface,
} from "../../interfaces/IERC165Updater";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes4",
        name: "interfaceID",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "supported",
        type: "bool",
      },
    ],
    name: "InterfaceSupportUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes4[]",
        name: "interfaceIDs",
        type: "bytes4[]",
      },
      {
        internalType: "bool[]",
        name: "support",
        type: "bool[]",
      },
    ],
    name: "updateSupportedInterfaces",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IERC165Updater__factory {
  static readonly abi = _abi;
  static createInterface(): IERC165UpdaterInterface {
    return new utils.Interface(_abi) as IERC165UpdaterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC165Updater {
    return new Contract(address, _abi, signerOrProvider) as IERC165Updater;
  }
}
