/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface RevertFacetInterface extends utils.Interface {
  functions: {
    "revertWithReason()": FunctionFragment;
    "revertWithoutReason()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "revertWithReason" | "revertWithoutReason"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "revertWithReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertWithoutReason",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "revertWithReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertWithoutReason",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RevertFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RevertFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    revertWithReason(overrides?: CallOverrides): Promise<[void]>;

    revertWithoutReason(overrides?: CallOverrides): Promise<[void]>;
  };

  revertWithReason(overrides?: CallOverrides): Promise<void>;

  revertWithoutReason(overrides?: CallOverrides): Promise<void>;

  callStatic: {
    revertWithReason(overrides?: CallOverrides): Promise<void>;

    revertWithoutReason(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    revertWithReason(overrides?: CallOverrides): Promise<BigNumber>;

    revertWithoutReason(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    revertWithReason(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revertWithoutReason(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
