/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  FallbackFacet,
  FallbackFacetInterface,
} from "../../../mocks/facets/FallbackFacet";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50605180601d6000396000f3fe608060405260166730a9fec57cb7ffad60c01b6018565b005b5056fea2646970667358221220c11f86097fa43b98a1014cb0018259add3bc0d3a95e7e48a235331f8b1266bd764736f6c63430008180033";

type FallbackFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FallbackFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FallbackFacet__factory extends ContractFactory {
  constructor(...args: FallbackFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<FallbackFacet> {
    return super.deploy(overrides || {}) as Promise<FallbackFacet>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): FallbackFacet {
    return super.attach(address) as FallbackFacet;
  }
  override connect(signer: Signer): FallbackFacet__factory {
    return super.connect(signer) as FallbackFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FallbackFacetInterface {
    return new utils.Interface(_abi) as FallbackFacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FallbackFacet {
    return new Contract(address, _abi, signerOrProvider) as FallbackFacet;
  }
}
