/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  Test1Facet,
  Test1FacetInterface,
} from "../../../mocks/facets/Test1Facet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "funcNum",
        type: "uint256",
      },
    ],
    name: "Test1Event",
    type: "event",
  },
  {
    inputs: [],
    name: "testFunc1",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "testFunc2",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "testFunc3",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610308806100206000396000f3fe6080604052600436106100345760003560e01c80630875236014610039578063561f5f89146100435780639a5fb5a81461004d575b600080fd5b610041610057565b005b61004b6100cd565b005b610055610143565b005b61006b67ec576fded8f8a6f360c01b6101b9565b61007f675279cf50e954551e60c01b6101b9565b6100936712ffdfa1d1e0011760c01b6101b9565b7f41a8f63e5febf1f2e807929cb5e5d306a0e5c430624865153e552c6bbd6c6feb60026040516100c3919061020b565b60405180910390a1565b6100e167ad8a0b0653f8c8d960c01b6101b9565b6100f56754e5cb594ad73d5760c01b6101b9565b61010967ebe96f92bdb1c47660c01b6101b9565b7f41a8f63e5febf1f2e807929cb5e5d306a0e5c430624865153e552c6bbd6c6feb60016040516101399190610261565b60405180910390a1565b610157674e84a7c71b55266460c01b6101b9565b61016b67fd85d2225c4cf2e760c01b6101b9565b61017f677fc2f8f018c73a8660c01b6101b9565b7f41a8f63e5febf1f2e807929cb5e5d306a0e5c430624865153e552c6bbd6c6feb60036040516101af91906102b7565b60405180910390a1565b50565b6000819050919050565b6000819050919050565b6000819050919050565b60006101f56101f06101eb846101bc565b6101d0565b6101c6565b9050919050565b610205816101da565b82525050565b600060208201905061022060008301846101fc565b92915050565b6000819050919050565b600061024b61024661024184610226565b6101d0565b6101c6565b9050919050565b61025b81610230565b82525050565b60006020820190506102766000830184610252565b92915050565b6000819050919050565b60006102a161029c6102978461027c565b6101d0565b6101c6565b9050919050565b6102b181610286565b82525050565b60006020820190506102cc60008301846102a8565b9291505056fea264697066735822122003d5436100868fa0996fc920080b91e0295b3e6be8f83beeb6f22a055255879c64736f6c63430008180033";

type Test1FacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Test1FacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Test1Facet__factory extends ContractFactory {
  constructor(...args: Test1FacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Test1Facet> {
    return super.deploy(overrides || {}) as Promise<Test1Facet>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Test1Facet {
    return super.attach(address) as Test1Facet;
  }
  override connect(signer: Signer): Test1Facet__factory {
    return super.connect(signer) as Test1Facet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Test1FacetInterface {
    return new utils.Interface(_abi) as Test1FacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Test1Facet {
    return new Contract(address, _abi, signerOrProvider) as Test1Facet;
  }
}
