/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDiamondCutFacet__factory } from "./IDiamondCutFacet__factory";
export { IDiamondLoupeFacet__factory } from "./IDiamondLoupeFacet__factory";
