/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IERC165UpdaterInterface extends utils.Interface {
  functions: {
    "updateSupportedInterfaces(bytes4[],bool[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "updateSupportedInterfaces"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "updateSupportedInterfaces",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<boolean>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "updateSupportedInterfaces",
    data: BytesLike
  ): Result;

  events: {
    "InterfaceSupportUpdated(bytes4,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "InterfaceSupportUpdated"): EventFragment;
}

export interface InterfaceSupportUpdatedEventObject {
  interfaceID: string;
  supported: boolean;
}
export type InterfaceSupportUpdatedEvent = TypedEvent<
  [string, boolean],
  InterfaceSupportUpdatedEventObject
>;

export type InterfaceSupportUpdatedEventFilter =
  TypedEventFilter<InterfaceSupportUpdatedEvent>;

export interface IERC165Updater extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC165UpdaterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  updateSupportedInterfaces(
    interfaceIDs: PromiseOrValue<BytesLike>[],
    support: PromiseOrValue<boolean>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "InterfaceSupportUpdated(bytes4,bool)"(
      interfaceID?: PromiseOrValue<BytesLike> | null,
      supported?: null
    ): InterfaceSupportUpdatedEventFilter;
    InterfaceSupportUpdated(
      interfaceID?: PromiseOrValue<BytesLike> | null,
      supported?: null
    ): InterfaceSupportUpdatedEventFilter;
  };

  estimateGas: {
    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    updateSupportedInterfaces(
      interfaceIDs: PromiseOrValue<BytesLike>[],
      support: PromiseOrValue<boolean>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
