/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as facets from "./facets";
export type { facets };
export type { IDiamond } from "./IDiamond";
export type { IDiamondCut } from "./IDiamondCut";
export type { IDiamondLoupe } from "./IDiamondLoupe";
export type { IERC165 } from "./IERC165";
export type { IERC165Updater } from "./IERC165Updater";
export type { IERC173 } from "./IERC173";
