/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDiamondCutFacet } from "./IDiamondCutFacet";
export type { IDiamondLoupeFacet } from "./IDiamondLoupeFacet";
